version: 0.0.1.8

signing:
  debug:
    store: $MOD_HOME/res/anddev.keystore
    pass: qwerty
    alias: anddev.keystore

  release:
    store: $MOD_HOME/res/anddev.keystore
    pass: qwerty
    alias: anddev.keystore

maps_key:
  debug: AIzaSyDiuDOLlqQhubJOJZ1hTUyUhewoVgrqNQE
  release: AIzaSyDiuDOLlqQhubJOJZ1hTUyUhewoVgrqNQE
