version: 1.0.3.8

signing:
  debug:
    store: $MOD_HOME/res/pk-mod.keystore
    pass: qwerty
    alias: pk-mod

  release:
    store: $MOD_HOME/res/pk-mod.keystore
    pass: qwerty
    alias: pk-mod

maps_key:
  debug: AIzaSyCKWltyu6lmzwos8gj1Yts7UjNw4MVC_4Y
  release: AIzaSyCKWltyu6lmzwos8gj1Yts7UjNw4MVC_4Y
